import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../globals.css";
import "../general.scss";
import App from "../App";
import "../index.scss";
import { ApiRequestProvider } from "@/provider/InterceptorProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Eco-v Energy",
  // description: "Generated by Abasotech",
};

export default function ModulesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="body-content">
        <App>
          <ApiRequestProvider>{children}</ApiRequestProvider>
        </App>
      </body>
    </html>
  );
}
