export enum MODULES { 
    MODULE_AFFILIATES = 'MODULE_AFFILIATES',
    MODULE_BUYS = 'MODULE_BUYS',
    MODULE_COMMISSIONS = 'MODULE_COMMISSIONS',
    MODULE_PAYS = 'MODULE_PAYS',
    MODULE_DOCUMENTS = 'MODULE_DOCUMENTS'
}